export enum CurrencyCode {
    EUR = 'EUR',
    USD = 'USD',
    JPY = 'JPY',
    BGN = 'BGN',
    CZK = 'CZK',
    DKK = 'DKK',
    GBP = 'GBP',
    HUF = 'HUF',
    PLN = 'PLN',
    RON = 'RON',
    SEK = 'SEK',
    CHF = 'CHF',
    ISK = 'ISK',
    NOK = 'NOK',
    HRK = 'HRK',
    RUB = 'RUB',
    TRY = 'TRY',
    AUD = 'AUD',
    BRL = 'BRL',
    CAD = 'CAD',
    CNY = 'CNY',
    HKD = 'HKD',
    IDR = 'IDR',
    ILS = 'ILS',
    INR = 'INR',
    KRW = 'KRW',
    MXN = 'MXN',
    MYR = 'MYR',
    NZD = 'NZD',
    PHP = 'PHP',
    SGD = 'SGD',
    THB = 'THB',
    ZAR = 'ZAR'
  }
  
  export const CurrencyNames: Record<CurrencyCode, string> = {
    [CurrencyCode.EUR]: 'Euro',
    [CurrencyCode.USD]: 'US Dollar',
    [CurrencyCode.JPY]: 'Japanese Yen',
    [CurrencyCode.BGN]: 'Bulgarian Lev',
    [CurrencyCode.CZK]: 'Czech Republic Koruna',
    [CurrencyCode.DKK]: 'Danish Krone',
    [CurrencyCode.GBP]: 'British Pound Sterling',
    [CurrencyCode.HUF]: 'Hungarian Forint',
    [CurrencyCode.PLN]: 'Polish Zloty',
    [CurrencyCode.RON]: 'Romanian Leu',
    [CurrencyCode.SEK]: 'Swedish Krona',
    [CurrencyCode.CHF]: 'Swiss Franc',
    [CurrencyCode.ISK]: 'Icelandic Króna',
    [CurrencyCode.NOK]: 'Norwegian Krone',
    [CurrencyCode.HRK]: 'Croatian Kuna',
    [CurrencyCode.RUB]: 'Russian Ruble',
    [CurrencyCode.TRY]: 'Turkish Lira',
    [CurrencyCode.AUD]: 'Australian Dollar',
    [CurrencyCode.BRL]: 'Brazilian Real',
    [CurrencyCode.CAD]: 'Canadian Dollar',
    [CurrencyCode.CNY]: 'Chinese Yuan',
    [CurrencyCode.HKD]: 'Hong Kong Dollar',
    [CurrencyCode.IDR]: 'Indonesian Rupiah',
    [CurrencyCode.ILS]: 'Israeli New Sheqel',
    [CurrencyCode.INR]: 'Indian Rupee',
    [CurrencyCode.KRW]: 'South Korean Won',
    [CurrencyCode.MXN]: 'Mexican Peso',
    [CurrencyCode.MYR]: 'Malaysian Ringgit',
    [CurrencyCode.NZD]: 'New Zealand Dollar',
    [CurrencyCode.PHP]: 'Philippine Peso',
    [CurrencyCode.SGD]: 'Singapore Dollar',
    [CurrencyCode.THB]: 'Thai Baht',
    [CurrencyCode.ZAR]: 'South African Rand'
  };

  